"""Parity tier — quantile (ELF / qgam-style) OOS pinball vs mgcv_rust.

gamrs's quantile fits must be on par with the mature `mgcv_rust` engine's
fast-OOS path, measured by out-of-sample pinball loss (the metric that
matters for quantile quality). The fixture
(`tests/fixtures/quantile_oos_hetero_n800_cr.json`, generated by
`scripts/gen_quantile_oos_reference.py`) embeds the train/test split and
mgcv_rust's per-τ OOS pinball, so this test needs no mgcv_rust import.

Bar: gamrs OOS pinball ≤ 1.05 × mgcv_rust's (at most 5% worse). Observed
gamrs is within ±1.5% and often better (τ ≥ 0.5).
"""

from __future__ import annotations

import numpy as np
import pytest

import gamrs

from conftest import load_fixture

pytestmark = pytest.mark.parity


def _pinball(y, q, tau):
    r = np.asarray(y) - np.asarray(q)
    return float(np.maximum(tau * r, (tau - 1.0) * r).mean())


def test_fast_oos_on_par_with_mgcv_rust():
    """gamrs `preset="fast_oos"` (heuristic σ + coverage calibration, ported
    from mgcv_rust) must match mgcv_rust's fast_oos OOS pinball within 5%.

    This is the apples-to-apples comparison: the fixture's reference pinball
    was generated by mgcv_rust's OWN fast_oos path. The fast path is CV-free,
    so it is the speed/quality balance the port targets."""
    fx = load_fixture("quantile_oos_hetero_n800_cr")
    x_tr = np.asarray(fx["inputs"]["x_train"], dtype=np.float64)
    y_tr = np.asarray(fx["inputs"]["y_train"], dtype=np.float64)
    x_te = np.asarray(fx["inputs"]["x_test"], dtype=np.float64)
    y_te = np.asarray(fx["inputs"]["y_test"], dtype=np.float64)
    per_tau = fx["mgcv_rust"]["per_tau"]
    k = int(fx["inputs"]["k"][0])

    for tau in fx["inputs"]["taus"]:
        ref = per_tau[str(tau)]["oos_pinball"]
        gam = gamrs.fit_quantile(x_tr, y_tr, tau, k=k, preset="fast_oos")
        # fast_oos = heuristic σ (sentinel 0.0), no CV, with coverage calibration.
        assert gam.sigma_ == 0.0
        assert gam.tune_info_ is None  # no CV ran
        assert gam.coverage_shift_ is not None and np.isfinite(gam.coverage_shift_)
        q_te = np.asarray(gam.predict(x_te.reshape(-1, 1))).ravel()
        gpb = _pinball(y_te, q_te, tau)
        ratio = gpb / ref
        assert ratio <= 1.05, (
            f"τ={tau}: gamrs fast_oos pinball {gpb:.5f} exceeds mgcv_rust {ref:.5f} "
            f"by {(ratio - 1) * 100:.1f}% (>5%)"
        )


@pytest.mark.slow
def test_quality_oos_calibration_runs():
    """`preset="quality_oos"` adds CV-tuned σ on top of coverage calibration.
    Verifies the CV path runs and still meets the OOS-pinball bar."""
    fx = load_fixture("quantile_oos_hetero_n800_cr")
    x_tr = np.asarray(fx["inputs"]["x_train"], dtype=np.float64)
    y_tr = np.asarray(fx["inputs"]["y_train"], dtype=np.float64)
    x_te = np.asarray(fx["inputs"]["x_test"], dtype=np.float64)
    y_te = np.asarray(fx["inputs"]["y_test"], dtype=np.float64)
    per_tau = fx["mgcv_rust"]["per_tau"]
    k = int(fx["inputs"]["k"][0])
    for tau in (0.1, 0.5, 0.9):
        gam = gamrs.fit_quantile(x_tr, y_tr, tau, k=k, preset="quality_oos")
        assert gam.sigma_ > 0 and gam.tune_info_ is not None  # CV ran
        assert gam.coverage_shift_ is not None
        q_te = np.asarray(gam.predict(x_te.reshape(-1, 1))).ravel()
        assert _pinball(y_te, q_te, tau) / per_tau[str(tau)]["oos_pinball"] <= 1.05
