#!/usr/bin/env Rscript
# A synthetic restatement of the `scat` flat-λ-ridge disagreement measured in
# docs/scat_adjuster_parity_2026-08.md.
#
#     Rscript scripts/r/gen_scat_flat_ridge_fixture.R
#
# WHAT THE SHAPE IS. The two terms where gamrs and mgcv disagreed most on the
# adjuster's single-term scat refits (`condition`, `quality`) share a geometry:
# a coarse ordinal predictor with ~16-19 distinct values against k=12, dollar-
# scale partial residuals whose signal is very nearly LINEAR in that predictor,
# and heavy-tailed noise. When the truth is linear, REML has no interior λ
# optimum -- the score descends monotonically toward the λ→∞ null-space limit,
# where the CR smooth collapses to a straight line (edf → 2). mgcv walks that
# ridge to sp ~ 1e7-1e9; gamrs's damped Newton stops part-way, leaving extra
# curvature that is worth hundreds of dollars on the fitted curve while costing
# well under one REML unit.
#
# This fixture reproduces that geometry with generated numbers, so the regime
# is regression-testable in a public repo (the real housing residuals stay in
# the gitignored data/ tree -- same constraint as docs/scat_parity_bug.md).
#
# The predictor mimics a 19-level condition score: 19 evenly spaced levels
# spanning 2.0 with a bell-ish, deliberately lopsided count profile, n = 620.
# Noise is scaled-t with 8 df, which mgcv's scat reads back as ν ≈ 6.55 (the
# neighbourhood it lands in on the real term), at σ = 32000 on a ~$550k level.
#
# The (seed, df) pair is chosen, not incidental: a t sample can carry enough
# spurious curvature that mgcv finds a genuine interior λ optimum instead, and
# then the fixture is testing a different regime. This one puts mgcv at
# edf = 2.010 with the score still falling as λ grows.
suppressMessages({library(mgcv); library(jsonlite)})

FIX <- "/home/alex/vibe_coding/gammon/tests/fixtures"
OUT <- "1d_scat_flat_lambda_ridge_n620_k12_cr.json"
SEED <- 1L
K <- 12L

set.seed(SEED)

levels_x <- seq(-1.0, 1.0, length.out = 19)                       # 19 distinct values
counts <- c(6, 18, 45, 22, 22, 24, 31, 28, 54, 62, 81, 69, 41, 43, 36, 20, 12, 5, 1)
stopifnot(length(counts) == 19)
x <- rep(levels_x, times = counts)
n <- length(x)                                                    # 620

# Linear truth -> no interior λ optimum. The tiny quadratic keeps the term from
# being EXACTLY in the null space (which would make the ridge degenerate rather
# than merely flat) while staying far below the noise.
f_true <- 548000 + 21000 * x + 900 * x^2
y <- f_true + 32000 * rt(n, df = 8) / sqrt(8 / (8 - 2))           # sd(noise) ~ 32000

fit <- gam(y ~ s(x, bs = "cr", k = K), method = "REML", family = scat())
th <- as.numeric(fit$family$getTheta(TRUE))
ux <- sort(unique(x))
pred <- as.numeric(predict(fit, newdata = data.frame(x = ux)))

# How flat is the ridge, and where does it bottom out? Recorded in the fixture
# so the Rust test can quote the cost of stopping short in REML units.
sp_ladder <- fit$sp[1] * 10^c(-4, -3, -2, -1, 0, 1, 2, 3)
ladder <- lapply(sp_ladder, function(s) {
  m <- gam(y ~ s(x, bs = "cr", k = K), method = "REML",
           family = scat(theta = th), sp = s)
  list(sp = as.numeric(s), reml = as.numeric(m$gcv.ubre), edf = sum(m$edf),
       predictions_unique_x = as.numeric(predict(m, newdata = data.frame(x = ux))))
})

obj <- list(
  schema_version = 1L,
  name = "1d_scat_flat_lambda_ridge_n620_k12_cr",
  description = paste(
    "Synthetic scat/CR fit whose REML score has NO interior optimum in λ:",
    "the signal is linear in a 19-level ordinal predictor, so the score",
    "descends monotonically to the λ→∞ straight-line limit (edf → 2).",
    "Restates the geometry of the `condition` / `quality` terms in",
    "docs/scat_adjuster_parity_2026-08.md without shipping real residuals."),
  provenance = paste(
    "Generated by scripts/r/gen_scat_flat_ridge_fixture.R, seed", SEED,
    "- fully synthetic, no customer data."),
  metadata = list(mgcv_version = as.character(packageVersion("mgcv")),
                  generated_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")),
  inputs = list(seed = SEED, n = n, d = 1L, k = K, bs = "cr", family = "scat",
                link = "identity", method = "REML",
                x_train = lapply(seq_len(n), function(i) x[i]),
                y_train = as.numeric(y)),
  unique_x = ux,
  mgcv_output = list(gam_reml = list(
    sp = as.numeric(fit$sp[1]), edf = sum(fit$edf), nu = th[1], sigma = th[2],
    reml = as.numeric(fit$gcv.ubre),
    predictions_unique_x = pred)),
  sp_ladder = ladder)

cat(toJSON(obj, auto_unbox = TRUE, digits = 17), file = file.path(FIX, OUT))
cat(sprintf("%s\n  n=%d  k=%d  n_unique=%d\n  mgcv sp=%.6g edf=%.4f nu=%.4f sigma=%.1f reml=%.4f\n",
            OUT, n, K, length(ux), fit$sp[1], sum(fit$edf), th[1], th[2], fit$gcv.ubre))
cat("  sp ladder (sp, REML, edf, max |Δ$| vs the free fit):\n")
for (e in ladder) {
  cat(sprintf("    %-12.4g  %10.4f  %7.4f  %10.1f\n", e$sp, e$reml, e$edf,
              max(abs(e$predictions_unique_x - pred))))
}
