#!/usr/bin/env Rscript
# A synthetic restatement of the saturated-basis `scat` term that exposed the
# `score_rank_adjustment` defect fixed in 0.13.0.
#
#     Rscript scripts/r/gen_scat_saturated_basis_fixture.R
#
# WHAT THE SHAPE IS. A coarse count-like predictor with only 5 distinct values
# against k = 5, so the CR basis is saturated: the smooth can interpolate the
# five level means exactly and the REML score's minimum in λ is therefore
# shallow. The counts are extremely lopsided ([6, 161, 432, 19, 2]) — two of
# the five levels carry a handful of rows each — and the response is on a
# ~$550k dollar scale with heavy-tailed noise. That combination is what makes
# the term a sensitive detector for a penalty-scale defect: a rank-off-by-one
# in log|λS| moved the fit ~30× in penalty and 3.3% in fitted dollars, while
# all three synthetic fixtures in tests/parity_scat.rs passed throughout.
#
# Unlike gen_scat_flat_ridge_fixture.R (no interior λ optimum at all), this one
# HAS an interior optimum — that is the distinction between the two fixtures,
# and the sp ladder below is recorded so the Rust test can assert it.
#
# Fully generated numbers. The regime is taken from a real adjuster term; none
# of the data is (same constraint as docs/scat_parity_bug.md — real housing
# residuals stay in the gitignored data/ tree).
#
# The (seed, df) pair is chosen, not incidental: on a saturated basis a t sample
# can easily carry enough spurious curvature to push mgcv to edf ≈ 4 (the whole
# basis) or enough noise to flatten it onto the straight-line limit (edf ≈ 2.00).
# Seed 165 puts mgcv at edf ≈ 2.39 with a genuine interior optimum, and the
# three mgcv arms (gam+REML, bam+REML, bam+fREML) agree to 1.2e-4 on the fitted
# level, so a single bound covers all three.
suppressMessages({library(mgcv); library(jsonlite)})

FIX <- "/home/alex/vibe_coding/gammon/tests/fixtures"
OUT <- "1d_scat_saturated_basis_n620_k5_cr.json"
SEED <- 165L
K <- 5L

# 5 evenly spaced levels, mean-centred (a count-like predictor: 0..4 less its
# weighted mean), with a deliberately lopsided count profile.
levels_x <- (0:4) - 1.7580645161290325
counts <- c(6L, 161L, 432L, 19L, 2L)
x <- rep(levels_x, times = counts)
n <- length(x)                                                    # 620
stopifnot(n == 620L, length(levels_x) == K)

set.seed(SEED)
# Mildly convex truth on a dollar scale, plus scaled-t noise (8 df), which
# mgcv's scat reads back as ν ≈ 7.2.
f_true <- 540000 + 16000 * x + 1500 * x^2
y <- f_true + 35000 * rt(n, df = 8) / sqrt(8 / (8 - 2))

dat <- data.frame(x = x, y = y)
ux <- sort(unique(x))
nd <- data.frame(x = ux)

arm <- function(fit) {
  th <- as.numeric(fit$family$getTheta(TRUE))
  list(sp = as.numeric(fit$sp[1]), edf = sum(fit$edf), nu = th[1], sigma = th[2],
       reml = as.numeric(fit$gcv.ubre),
       predictions_unique_x = as.numeric(predict(fit, newdata = nd)))
}

f_gam  <- gam(y ~ s(x, bs = "cr", k = K), method = "REML",  family = scat(), data = dat)
f_bamr <- bam(y ~ s(x, bs = "cr", k = K), method = "REML",  family = scat(), data = dat)
f_bamf <- bam(y ~ s(x, bs = "cr", k = K), method = "fREML", family = scat(), data = dat)

# Where does the score bottom out, and how shallow is it? Recorded so the Rust
# test can assert this fixture really has an interior optimum (as opposed to the
# flat-ridge fixture, which has none).
th <- as.numeric(f_gam$family$getTheta(TRUE))
ladder <- lapply(f_gam$sp[1] * 10^c(-3, -2, -1, 0, 1, 2, 3), function(s) {
  m <- gam(y ~ s(x, bs = "cr", k = K), method = "REML",
           family = scat(theta = th), sp = s, data = dat)
  list(sp = as.numeric(s), reml = as.numeric(m$gcv.ubre), edf = sum(m$edf),
       predictions_unique_x = as.numeric(predict(m, newdata = nd)))
})

obj <- list(
  schema_version = 1L,
  name = "1d_scat_saturated_basis_n620_k5_cr",
  description = paste(
    "Synthetic scat/CR fit on a saturated basis: 5 distinct x against k = 5,",
    "counts [6, 161, 432, 19, 2], dollar-scale response, heavy-tailed noise.",
    "The REML minimum in lambda is shallow but interior, which is what makes",
    "the term sensitive to the scale of the log|lambda.S| term (the 0.13.0",
    "score_rank_adjustment defect)."),
  provenance = paste(
    "Generated by scripts/r/gen_scat_saturated_basis_fixture.R, seed", SEED,
    "- fully synthetic, no customer data. The geometry (n, k, level counts,",
    "response scale) restates a real single-term adjuster refit; the numbers",
    "do not come from it."),
  metadata = list(mgcv_version = as.character(packageVersion("mgcv")),
                  generated_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")),
  inputs = list(seed = SEED, n = n, d = 1L, k = K, bs = "cr", family = "scat",
                link = "identity", method = "REML",
                x_train = lapply(seq_len(n), function(i) c(x[i])),
                y_train = as.numeric(y)),
  unique_x = ux,
  mgcv_output = list(gam_reml = arm(f_gam), bam_reml = arm(f_bamr),
                     bam_freml = arm(f_bamf)),
  sp_ladder = ladder)

cat(toJSON(obj, auto_unbox = TRUE, digits = 17), file = file.path(FIX, OUT))
cat(sprintf("%s\n  n=%d k=%d n_unique=%d\n", OUT, n, K, length(ux)))
for (nm in c("gam_reml", "bam_reml", "bam_freml")) {
  a <- obj$mgcv_output[[nm]]
  cat(sprintf("  %-10s sp=%.6g edf=%.4f nu=%.4f sigma=%.1f reml=%.4f\n",
              nm, a$sp, a$edf, a$nu, a$sigma, a$reml))
}
cat("  sp ladder (sp, REML, edf, max |Δ$| vs the free fit):\n")
p0 <- obj$mgcv_output$gam_reml$predictions_unique_x
for (e in ladder) {
  cat(sprintf("    %-12.4g %12.4f %8.4f %10.1f\n", e$sp, e$reml, e$edf,
              max(abs(e$predictions_unique_x - p0))))
}
